### ISSUE TITLE
Where can I find this ACL paper?

### ISSUE THREAD

**Issue by shaoyijia** [bzGeng/TPEM#1]
Hello! Can you kindly share a link of this ACL paper? I have searched for a long time but still couldn't find it. Thanks.

**Comment by bzGeng** [comment]
Hello! Thank you for your attention to our work. As ACL'21 meeting hasn't started yet, this work has not been officially published. But I've just submitted it to arvix. Please wait for a while, and I will inform you as soon as the verify procedure has finished.

**Comment by bzGeng** [comment]
By the way, I have upload the paper's PDF if it can help you!

**Comment by shaoyijia** [comment]
Thank you for your early reply. This is really helpful!
